"""add servings table and update food_logs

Revision ID: 559733462727
Revises: 083b78b306dd
Create Date: 2026-02-23 14:37:11.757959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559733462727'
down_revision: Union[str, Sequence[str], None] = '083b78b306dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # servings table
    op.create_table('servings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('food_id', sa.UUID(), nullable=False),
        sa.Column('serving_unit', sa.String(length=50), nullable=False),
        sa.Column('number_of_units', sa.Float(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('calories_kcal', sa.Float(), nullable=False),
        sa.Column('fat_g', sa.Float(), nullable=False),
        sa.Column('cholesterol_mg', sa.Float(), nullable=False),
        sa.Column('protein_g', sa.Float(), nullable=False),
        sa.Column('carbohydrate_g', sa.Float(), nullable=False),
        sa.Column('fiber_g', sa.Float(), nullable=False),
        sa.Column('sugar_g', sa.Float(), nullable=False),
        sa.Column('sodium_mg', sa.Float(), nullable=False),
        sa.Column('kalium_mg', sa.Float(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # comments table
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # food_logs table
    op.add_column('food_logs', sa.Column('serving_id', sa.UUID(), nullable=False))
    op.add_column('food_logs', sa.Column('number_of_units', sa.Float(), nullable=False))
    op.alter_column('food_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'food_logs', 'servings', ['serving_id'], ['id'])
    op.drop_column('food_logs', 'weight_grams')
    op.drop_column('food_logs', 'fats')
    op.drop_column('food_logs', 'carbohydrates')
    op.drop_column('food_logs', 'proteins')
    op.drop_column('food_logs', 'calories')
    op.add_column('foods', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('foods', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.add_column('foods', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False))
    op.alter_column('foods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # foods table
    op.drop_column('foods', 'cholesterol_per_100g_mg')
    op.drop_column('foods', 'instance_weight_g')
    op.drop_column('foods', 'sodium_per_100g_mg')
    op.drop_column('foods', 'kalium_per_100g_mg')
    op.drop_column('foods', 'protein_per_100g_g')
    op.drop_column('foods', 'fiber_per_100g_g')
    op.drop_column('foods', 'fat_per_100g_g')
    op.drop_column('foods', 'calories_per_100g_kcal')
    op.drop_column('foods', 'sugar_per_100g_g')
    op.drop_column('foods', 'carbohydrate_per_100g_g')

    # recipes table
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # users table
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # users table
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    
    # recipes table
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    
    # foods table
    op.add_column('foods', sa.Column('carbohydrate_per_100g_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('sugar_per_100g_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('calories_per_100g_kcal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('fat_per_100g_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('fiber_per_100g_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('protein_per_100g_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('kalium_per_100g_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('sodium_per_100g_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('instance_weight_g', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('cholesterol_per_100g_mg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('foods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('foods', 'search_vector')
    op.drop_column('foods', 'subcategory')
    op.drop_column('foods', 'category')

    # food_logs table
    op.add_column('food_logs', sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_logs', sa.Column('proteins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_logs', sa.Column('carbohydrates', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_logs', sa.Column('fats', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('food_logs', sa.Column('weight_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'food_logs', type_='foreignkey')
    op.alter_column('food_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('food_logs', 'number_of_units')
    op.drop_column('food_logs', 'serving_id')

    # comments table
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    
    # servings table
    op.drop_table('servings')
    # ### end Alembic commands ###
